name: Call Another Repository

on:
  push:
    branches:
      - main
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout current repository
        uses: actions/checkout@v3
      - name: checkout another repository
        uses: actions/checkout@v3
        with:
          repository: Ram610/githubActions
          token: ${{secrets.PAT}}
      - name: Run script from another repository
        run: |
          echo "debug permissions: $GITHUB_REPOSITORY"
          echo "Actor : $GITHUB_ACTOR"
          echo "Token permissions- 2"
          curl -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/Ram610/githubActions
          node ./testNew.js
        
